[package]
name = "md-prep"
version = "0.1.0"
authors = ["Keverne Louison <39338001+Keverne@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
